"use strict";

const { createAdminDomainAuth } = require("./domain-admin-auth");
const { createAdminClientDomain } = require("./domain-clients");
const { createAdminDomainFormatters } = require("./domain-formatters");
const { createAdminLeadDomain } = require("./domain-leads");
const { createAdminOrderMutationDomain } = require("./domain-order-mutations");
const { createAdminOrderDomain } = require("./domain-orders");
const { createAdminDomainSharedHelpers } = require("./domain-shared");
const {
  getEntryOrderCompletionData: getPersistedOrderCompletionData,
  getEntryOrderPolicyAcceptanceData: getPersistedOrderPolicyAcceptanceData,
  getEntryOrderState: getPersistedOrderState,
  getEntryPayload: getPersistedEntryPayload,
  getEntryPaymentState: getPersistedPaymentState,
  setEntryOrderState,
  setEntryPaymentState,
} = require("../admin-order-state");

function createAdminDomainHelpers(deps = {}) {
  const {
    ADMIN_CHALLENGE_COOKIE,
    ADMIN_ORDERS_PATH,
    ADMIN_QUOTE_OPS_PATH,
    ADMIN_SESSION_COOKIE,
    ADMIN_STAFF_PATH,
    GOOGLE_PLACES_API_KEY,
    ORDER_ASSIGNMENT_VALUES,
    PERF_ENDPOINT_ENABLED,
    PERF_ENDPOINT_TOKEN,
    QRCode,
    SITE_ORIGIN,
    adminAuth,
    adminSharedRenderers,
    escapeHtmlText,
    getClientAddress,
    getQuoteTokenSecret,
    getQuoteTokenTtlSeconds,
    getRequestUrl,
    loadLeadConnectorConfig,
    loadSupabaseQuoteOpsConfig,
    normalizeString,
    parseCookies,
    shouldTrustProxyHeaders,
    shouldUseSecureCookies,
  } = deps;
  const ADMIN_TIME_ZONE = "America/Chicago";

  const { getAdminAuthState, getAdminCookieOptions } = createAdminDomainAuth({
    ADMIN_CHALLENGE_COOKIE,
    ADMIN_SESSION_COOKIE,
    GOOGLE_PLACES_API_KEY,
    PERF_ENDPOINT_ENABLED,
    PERF_ENDPOINT_TOKEN,
    adminAuth,
    getClientAddress,
    getQuoteTokenSecret,
    getQuoteTokenTtlSeconds,
    loadLeadConnectorConfig,
    loadSupabaseQuoteOpsConfig,
    normalizeString,
    parseCookies,
    shouldTrustProxyHeaders,
    shouldUseSecureCookies,
  });

  const {
    buildAdminQrMarkup,
    buildAdminRedirectPath,
    buildQuoteOpsReturnPath,
    buildStaffReturnPath,
    cloneSerializable,
    formatBooleanLabel,
    formatCountList,
    getEntryAdminLeadData,
    getEntryAdminOrderData,
    getEntryAdminSmsData,
    getEntryCalculatorData,
    getEntryOrderPolicyAcceptanceData,
    getEntryPayload,
    getEntryPaymentData,
    getEntrySmsHistory,
    maskSecretPreview,
    normalizeAdminSmsHistoryEntries,
    setNormalizeLeadTaskDueAt,
  } = createAdminDomainSharedHelpers({
    ADMIN_QUOTE_OPS_PATH,
    ADMIN_STAFF_PATH,
    QRCode,
    SITE_ORIGIN,
    escapeHtmlText,
    getPersistedEntryPayload,
    getPersistedOrderPolicyAcceptanceData,
    getPersistedOrderState,
    getPersistedPaymentState,
    normalizeString,
  });

  const {
    formatCurrencyAmount,
    formatAdminDateTime,
    formatAdminServiceLabel,
    formatOrderCountLabel,
    formatStaffCountLabel,
    formatAdminCalendarDate,
    formatAdminClockTime,
    normalizeAdminOrderDateInput,
    formatAdminOrderDateInputValue,
    normalizeAdminOrderPriceInput,
    formatAdminOrderPriceInputValue,
    normalizeAdminOrderTimeInput,
    formatAdminOrderTimeInputValue,
    formatAdminScheduleLabel,
    toAdminScheduleTimestamp,
    formatStaffStatusLabel,
    formatAssignmentStatusLabel,
    renderStaffStatusBadge,
    renderAssignmentStatusBadge,
  } = createAdminDomainFormatters({
    ADMIN_TIME_ZONE,
    adminSharedRenderers,
    normalizeString,
  });

  const {
    buildStaffPlanningContext,
    normalizeOrderServiceType,
    normalizeOrderFrequency,
    normalizeOrderPaymentStatus,
    normalizeOrderPaymentMethod,
    normalizeOrderStatus,
    getOrderSelectedDate,
    getOrderSelectedTime,
    getOrderServiceType,
    getOrderServiceDurationMinutes,
    getOrderFrequency,
    getOrderAssignedStaff,
    getOrderPaymentStatus,
    getOrderPaymentMethod,
    isOrderCreatedEntry,
    getOrderStatus,
    collectAdminOrderRecords,
    filterAdminOrderRecords,
    countOrdersByStatus,
    getOrdersFilters,
    buildOrdersReturnPath,
  } = createAdminOrderDomain({
    ADMIN_ORDERS_PATH,
    ORDER_ASSIGNMENT_VALUES,
    SITE_ORIGIN,
    formatAdminScheduleLabel,
    getEntryAdminOrderData,
    getEntryCalculatorData,
    getEntryOrderPolicyAcceptanceData,
    getEntryPaymentData,
    getRequestUrl,
    normalizeAdminOrderDateInput,
    normalizeAdminOrderTimeInput,
    normalizeString,
    toAdminScheduleTimestamp,
  });

  const {
    applyOrderEntryUpdates,
    applyPaymentEntryUpdates,
    buildRecurringOrderSubmission,
    getEntryOrderCompletionData,
  } = createAdminOrderMutationDomain({
    ADMIN_ORDERS_PATH,
    cloneSerializable,
    formatAdminScheduleLabel,
    getEntryAdminOrderData,
    getEntryAdminSmsData,
    getEntryCalculatorData,
    getEntryPayload,
    getEntryPaymentData,
    getEntrySmsHistory,
    getOrderFrequency,
    getOrderSelectedDate,
    getOrderSelectedTime,
    getOrderServiceType,
    getOrderServiceDurationMinutes,
    getOrderStatus,
    getPersistedOrderCompletionData,
    isOrderCreatedEntry,
    normalizeAdminOrderDateInput,
    normalizeAdminOrderPriceInput,
    normalizeAdminOrderTimeInput,
    normalizeAdminSmsHistoryEntries,
    normalizeOrderFrequency,
    normalizeOrderPaymentMethod,
    normalizeOrderPaymentStatus,
    normalizeOrderStatus,
    normalizeString,
    setEntryOrderState,
    setEntryPaymentState,
  });

  const {
    normalizeLeadStatus,
    formatLeadStatusLabel,
    normalizeLeadTaskDueAt,
    getLeadStatus,
    getEntryLeadTasks,
    getEntryOpenLeadTask,
    applyLeadEntryUpdates,
    getQuoteOpsFilters,
  } = createAdminLeadDomain({
    applyOrderEntryUpdates,
    getEntryAdminLeadData,
    getEntryAdminSmsData,
    getEntryPayload,
    getEntrySmsHistory,
    getRequestUrl,
    isOrderCreatedEntry,
    normalizeAdminSmsHistoryEntries,
    normalizeString,
  });

  setNormalizeLeadTaskDueAt(normalizeLeadTaskDueAt);

  const {
    applyClientEntryUpdates,
    getAdminClientsFilters,
    collectAdminClientRecords,
    filterAdminClientRecords,
  } = createAdminClientDomain({
    getEntryAdminSmsData,
    getEntryCalculatorData,
    getEntryPayload,
    getEntrySmsHistory,
    getRequestUrl,
    normalizeAdminSmsHistoryEntries,
    normalizeString,
  });

  return {
    applyPaymentEntryUpdates,
    applyLeadEntryUpdates,
    applyClientEntryUpdates,
    applyOrderEntryUpdates,
    buildRecurringOrderSubmission,
    buildAdminQrMarkup,
    buildAdminRedirectPath,
    buildOrdersReturnPath,
    buildQuoteOpsReturnPath,
    buildStaffPlanningContext,
    collectAdminClientRecords,
    collectAdminOrderRecords,
    countOrdersByStatus,
    filterAdminClientRecords,
    filterAdminOrderRecords,
    formatAdminCalendarDate,
    formatAdminClockTime,
    formatAdminDateTime,
    formatAdminOrderDateInputValue,
    formatAdminOrderPriceInputValue,
    formatAdminOrderTimeInputValue,
    formatAdminServiceLabel,
    formatAssignmentStatusLabel,
    formatCurrencyAmount,
    formatLeadStatusLabel,
    formatOrderCountLabel,
    formatStaffCountLabel,
    formatStaffStatusLabel,
    getAdminAuthState,
    getAdminCookieOptions,
    getAdminClientsFilters,
    getEntryAdminOrderData,
    getEntryAdminLeadData,
    getEntryLeadTasks,
    getEntryOpenLeadTask,
    getEntryOrderCompletionData,
    getEntryOrderPolicyAcceptanceData,
    getLeadStatus,
    getOrderStatus,
    getOrdersFilters,
    getQuoteOpsFilters,
    isOrderCreatedEntry,
    normalizeLeadStatus,
    normalizeOrderStatus,
    renderAssignmentStatusBadge,
    renderStaffStatusBadge,
  };
}

module.exports = {
  createAdminDomainHelpers,
};
